# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
install:
  - Rscript -e 'install.packages(c("magrittr", "commonmark", "crayon", "hunspell", "knitr", "purrr",
  "tokenizers", "xml2", "pdftools", "rstudioapi"), repos = "http://cran.rstudio.com")'


